from fastapi import APIRouter, Depends, Body, HTTPException
from app.services.rlaif import RLAIFService, get_rlaif_service
from app.db.database_clients import get_db_session
from sqlalchemy.ext.asyncio import AsyncSession
from typing import List, Dict, Optional
import json

rlaif_router = APIRouter()

@rlaif_router.get("/accuracy-log")
async def get_accuracy_log(zone_id: Optional[str] = None, rlaif_service: RLAIFService = Depends(get_rlaif_service)):
    """Fetch the historical improvement curve for the model accuracy (MAPE)."""
    # Simplified: query RLAIFLog table for historical mape_before/mape_after
    return {
        "logs": [
            {"iteration": 1, "mape_before": 0.14, "mape_after": 0.12, "timestamp": "2026-03-27T09:00:00Z"},
            {"iteration": 2, "mape_before": 0.12, "mape_after": 0.09, "timestamp": "2026-03-27T09:30:00Z"},
            {"iteration": 3, "mape_before": 0.09, "mape_after": 0.07, "timestamp": "2026-03-27T10:00:00Z"}
        ]
    }

@rlaif_router.get("/critiques")
async def get_judge_critiques(zone_id: Optional[str] = None):
    """Retrieve the recent critiques generated by the AI judge."""
    # Simplified: query RLAIFLog or separate critiques table
    return [
        {"root_cause": "Unexpected drop in solar output due to local cloud cover.", "suggested_data": "Synthetic solar dip scenarios."}
    ]

@rlaif_router.post("/trigger")
async def trigger_manual_retrain(
    zone_id: str = Body(..., embed=True),
    rlaif_service: RLAIFService = Depends(get_rlaif_service)
):
    """Manually trigger the RLAIF self-improvement loop for a specific zone."""
    result = await rlaif_service.trigger_retraining_loop(zone_id)
    return result

router = rlaif_router
